// Runs in the EA web app's main world.
// Preset definitions for the Squad Builder view.
//
// Generic preset template (all fields, with defaults):
// {
//     label:              string,   // Display name shown in the dropdown
//     challengeName:            string,   // Must match the SBC challenge title exactly
//
//     // Toggles: true = ON, false = OFF, null = leave as-is
//     useConcept:         null,     // Use Concept Players
//     untradeablesOnly:   null,     // Untradeables Only
//     excludeActiveSquad: null,     // Exclude Active Squad Players
//     ignorePosition:     null,     // Ignore Position
//
//     // Dropdowns: null = leave as-is
//     sortBy:   null,   // "Rating High to Low" | "Rating Low to High"
//     storage:  null,   // "Any" | "My Club" | "SBC Storage"
//     quality:  null,   // "Bronze" | "Silver" | "Gold"
//     rarity:   null,   // "Common" | "Rare" | "Special"
//     league:   null,   // "BEL 1" | "ENG 1" | "ESP 1" | "FRA 1" | "GER 1" | "ITA1" | "NED 1" | "POR 1"
//
//     // OVR inputs: null = leave as-is
//     minOvr:   null,   // integer 45-99
//     maxOvr:   null,   // integer 45-99
// }

var fc26 = fc26 || {};

fc26.presets = [
    {
        label: 'Lowest Any',
        challengeName: 'Daily Bronze Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Bronze',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Lowest SBC Storage',
        challengeName: 'Daily Bronze Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Bronze',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Daily Silver Upgrade',
        challengeName: 'Daily Silver Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'My Club',
        quality: 'Silver',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Daily Rare Gold Upgrade',
        challengeName: 'Daily Rare Gold Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Mixed Leagues Upgrade',
        challengeName: 'Mixed Leagues Upgrade',
        excludeActiveSquad: null,
        ignorePosition: null,
        sortBy: null,
        storage: 'My Club',
        quality: null,
        rarity: null,
        minOvr: 45,
        maxOvr: 74,
        league: 'BEL 1',
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: '5 of 10 81+ Player Pick',
        challengeName: '5 of 10 81+ Player Pick',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: null,
        rarity: 'Common',
        minOvr: null,
        maxOvr: 80,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Lowest - Any',
        challengeName: '5x 77+ Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: null,
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Lowest - SBC Storage',
        challengeName: '5x 77+ Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: null,
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: '1 of 5 82+ Player Pick',
        challengeName: '1 of 5 82+ Player Pick',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: null,
        quality: null,
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 81,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: '3x 87-90 Upgrade',
        challengeName: '3x 87-90 Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'My Club',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 82,
        maxOvr: 83,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: '2x 84+ Upgrade',
        challengeName: '2x 84+ Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: null,
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 82,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: '84+ TOTW Upgrade',
        challengeName: '84+ TOTW Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 83,
        maxOvr: 84,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
    {
        label: 'Provisions Upgrade',
        challengeName: 'Provisions Upgrade',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: null,
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 85,
        maxOvr: 85,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
    },
];
