// Runs in the EA web app's main world.
// Preset definitions for the Squad Builder view.
// challengeName usage:
// - challengeName is the key in fc26SbcPresets.presets
// - each key must match the SBC challenge title exactly
// - each value is the preset list for that challenge
//
// Generic preset template (all fields, with defaults):
// {
//     label:              string,   // Display name shown in the dropdown
//
//     // Toggles: true = ON, false = OFF, null = leave as-is
//     useConcept:         null,     // Use Concept Players
//     untradeablesOnly:   null,     // Untradeables Only
//     excludeActiveSquad: null,     // Exclude Active Squad Players
//     ignorePosition:     null,     // Ignore Position
//
//     // Dropdowns: null = leave as-is
//     sortBy:   null,   // "Rating High to Low" | "Rating Low to High"
//     storage:  null,   // "Any" | "My Club" | "SBC Storage"
//     quality:  null,   // "Bronze" | "Silver" | "Gold"
//     rarity:   null,   // "Common" | "Rare" | "Special"
//     league:   null,   // "BEL 1" | "ENG 1" | "ESP 1" | "FRA 1" | "GER 1" | "ITA1" | "NED 1" | "POR 1"
//
//     // OVR inputs: null = leave as-is
//     minOvr:   null,   // integer 45-99
//     maxOvr:   null,   // integer 45-99
// }

var fc26SbcPresets = fc26SbcPresets || {};

fc26SbcPresets.presets = {
    'Daily Bronze Upgrade': [
        {
        label: 'L → H Bronze (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Bronze',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Bronze (Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Bronze',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Daily Silver Upgrade': [
        {
        label: 'L → H Silver (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Silver',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Silver (Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Silver',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Silver Upgrade': [
        {
        label: 'L → H Silver (Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Silver',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Silver (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Silver',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Daily Common Gold Upgrade': [
        {
        label: 'L → H Bronze (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Bronze',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Silver (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Silver',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Bronze (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Bronze',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Silver (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Silver',
        rarity: null,
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Daily Rare Gold Upgrade': [
        {
        label: 'L → H Gold Common (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Common (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'FOF Glory Hunters Crafting Upgrade': [
        {
        label: 'L → H Gold Common (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Common (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'ROSHN Saudi League & SuperLiga': [
        {
        label: 'ROSHN Saudi League',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: 45,
        maxOvr: 75,
        league: 'SAU 1',
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'SuperLiga',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: 45,
        maxOvr: 75,
        league: 'ROM 1',
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'ROSHN Saudi League (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: 45,
        maxOvr: 75,
        league: 'SAU 1',
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Gold Challenge': [
        {
        label: 'L → H Gold Common (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Common (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '87-Rated Squad': [
        {
        label: 'Highest 86-87 OVR (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 86,
        maxOvr: 87,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Highest 86-87 OVR (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 86,
        maxOvr: 87,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '88-Rated Squad': [
        {
        label: 'Highest 87-88 OVR (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 87,
        maxOvr: 88,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Highest 87-88 OVR (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 87,
        maxOvr: 88,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '89-Rated Squad': [
        {
        label: 'Highest 88-89 OVR (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 88,
        maxOvr: 89,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Highest 88-89 OVR (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 88,
        maxOvr: 89,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Mixed Leagues Upgrade': [
        {
        label: 'Mixed Leagues Upgrade (Any)',
        excludeActiveSquad: null,
        ignorePosition: null,
        sortBy: null,
        storage: 'Any',
        quality: null,
        rarity: null,
        minOvr: 45,
        maxOvr: 74,
        league: 'BEL 1',
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Mixed Leagues Upgrade (SBC Storage)',
        excludeActiveSquad: null,
        ignorePosition: null,
        sortBy: null,
        storage: 'SBC Storage',
        quality: null,
        rarity: null,
        minOvr: 45,
        maxOvr: 74,
        league: 'BEL 1',
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '5 of 10 81+ Player Pick': [
        {
        label: 'L → H Gold Common (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: null,
        rarity: 'Common',
        minOvr: null,
        maxOvr: 80,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Common (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: null,
        rarity: 'Common',
        minOvr: null,
        maxOvr: 80,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '5x 77+ Upgrade': [
        {
        label: 'L → H Gold Common (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Common (Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Common',
        minOvr: null,
        maxOvr: null,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '1 of 5 82+ Player Pick': [
        {
        label: 'L → H Gold Rare (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 81,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Rare (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 81,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '1 of 3 83+ Player Pick': [
        {
        label: 'L → H Gold Rare (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 82,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Rare (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 82,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '3x 87-90 Upgrade': [
        {
        label: 'Highest 82-83 OVR (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 82,
        maxOvr: 83,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Highest 82-83 OVR (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 82,
        maxOvr: 83,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '2x 84+ Upgrade': [
        {
        label: 'L → H Gold Rare (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 82,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Rare (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: null,
        maxOvr: 82,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '10x 84+ Upgrade': [
        {
        label: 'L → H Gold Rare (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 82,
        maxOvr: 83,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'L → H Gold Rare (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 82,
        maxOvr: 83,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    '84+ TOTW Upgrade': [
        {
        label: 'Highest 83-84 OVR (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 83,
        maxOvr: 84,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Highest 83-84 OVR (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating High to Low',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 83,
        maxOvr: 84,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
    'Provisions Upgrade': [
        {
        label: 'Exact 85 OVR (Any)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'Any',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 85,
        maxOvr: 85,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
        {
        label: 'Exact 85 OVR (SBC Storage)',
        excludeActiveSquad: true,
        ignorePosition: true,
        sortBy: 'Rating Low to High',
        storage: 'SBC Storage',
        quality: 'Gold',
        rarity: 'Rare',
        minOvr: 85,
        maxOvr: 85,
        league: null,
        useConcept: null,
        untradeablesOnly: null,
        },
    ],
};
