// Runs in the EA web app's main world.
// Preset definitions for the Squad Builder view.
// challengeName usage:
// - challengeName is the key in fc26SbcPresets.presets
// - each key must match the SBC challenge title exactly
// - each value is the preset list for that challenge
//
// Generic preset template (all fields, with defaults):
// {
//     label:              string,   // Display name shown in the dropdown
//
//     // Toggles: true = ON, false = OFF, null = leave as-is
//     useConcept:         null,     // Use Concept Players
//     untradeablesOnly:   null,     // Untradeables Only
//     excludeActiveSquad: null,     // Exclude Active Squad Players
//     ignorePosition:     null,     // Ignore Position
//
//     // Dropdowns: null = leave as-is
//     sortBy:   null,   // "Rating High to Low" | "Rating Low to High"
//     storage:  null,   // "Any" | "My Club" | "SBC Storage"
//     quality:  null,   // "Bronze" | "Silver" | "Gold"
//     rarity:   null,   // "Common" | "Rare" | "Special"
//     league:   null,   // "BEL 1" | "ENG 1" | "ESP 1" | "FRA 1" | "GER 1" | "ITA1" | "NED 1" | "POR 1"
//
//     // OVR inputs: null = leave as-is
//     minOvr:   null,   // integer 45-99
//     maxOvr:   null,   // integer 45-99
// }

var fc26SbcPresets = fc26SbcPresets || {};

fc26SbcPresets.presets = {
    'Daily Bronze Upgrade': [
        {
            label: 'L → H Bronze (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Bronze',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Bronze (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Bronze',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Daily Silver Upgrade': [
        {
            label: 'L → H Silver (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Silver',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Silver (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Silver',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Silver Upgrade': [
        {
            label: 'L → H Silver (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Silver',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Silver (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Silver',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Daily Common Gold Upgrade': [
        {
            label: 'L → H Bronze (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Bronze',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Silver (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Silver',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Bronze (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Bronze',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Silver (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Silver',
            rarity: null,
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Daily Rare Gold Upgrade': [
        {
            label: 'L → H Gold Common (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Common (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
        'Grind Upgrade': [
        {
            label: '84 → 83 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 83,
            maxOvr: 84,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '84 → 83 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 83,
            maxOvr: 84,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],    
    'FOF Glory Hunters Crafting Upgrade': [
        {
            label: 'L → H Gold Common (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Common (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'ROSHN Saudi League & SuperLiga': [
        {
            label: 'ROSHN Saudi League (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 45,
            maxOvr: 75,
            league: 'SAU 1',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'SuperLiga (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 45,
            maxOvr: 75,
            league: 'ROM 1',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Serie BKT & Bundesliga 2': [
        {
            label: 'Serie BKT (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 45,
            maxOvr: 75,
            league: 'ITA 2',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'Bundesliga 2 (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 45,
            maxOvr: 75,
            league: 'GER 2',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Ligue 2 BKT & LALIGA HyperMotion': [
        {
            label: 'Ligue 2 BKT (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 60,
            maxOvr: 75,
            league: 'FRA 2',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'LALIGA HyperMotion (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 60,
            maxOvr: 75,
            league: 'ESP 2',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'MLS & EFL Championship': [
        {
            label: 'MLS (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 69,
            maxOvr: 79,
            league: 'MLS',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'EFL Championship (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 69,
            maxOvr: 79,
            league: 'ENG 2',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Liga Portugal & 1A Pro League': [
        {
            label: 'Liga Portugal (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 60,
            maxOvr: 75,
            league: 'POR 1',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '1A Pro League (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 60,
            maxOvr: 75,
            league: 'BEL 1',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Ligue 1 & Eredivisie': [
        {
            label: 'Ligue 1 (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 65,
            maxOvr: 80,
            league: 'FRA 1',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'Eredivisie (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 65,
            maxOvr: 80,
            league: 'NED 1',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Bundesliga & Serie A': [
        {
            label: 'Bundesliga (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 75,
            maxOvr: 80,
            league: 'GER 1',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'Serie A (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 75,
            maxOvr: 80,
            league: 'ITA 1',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Premier League & LALIGA': [
        {
            label: 'Premier League (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 75,
            maxOvr: 82,
            league: 'ENG 1',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'LALIGA (Any)',
            excludeActiveSquad: true,
            ignorePosition: false,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 75,
            maxOvr: 82,
            league: 'ESP 1',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],    
    'Gold Challenge': [
        {
            label: 'L → H Gold Common (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Common (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '83-Rated Squad': [
        {
            label: '83 → 82 Any (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Any',
            minOvr: 82,
            maxOvr: 83,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '83 → 82 Any (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Any',
            minOvr: 82,
            maxOvr: 83,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '84-Rated Squad': [
        {
            label: '84 → 83 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 83,
            maxOvr: 84,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '84 → 83 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 83,
            maxOvr: 84,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '85-Rated Squad': [
        {
            label: '85 → 84 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 84,
            maxOvr: 85,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '85 → 84 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 86,
            maxOvr: 87,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '86-Rated Squad': [
        {
            label: '86 → 85 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 85,
            maxOvr: 86,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '86 → 85 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 85,
            maxOvr: 86,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],    
    '87-Rated Squad': [
        {
            label: '87 → 86 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 86,
            maxOvr: 87,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '87 → 86 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 86,
            maxOvr: 87,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '88-Rated Squad': [
        {
            label: '88 → 87 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 87,
            maxOvr: 88,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '88 → 87 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 87,
            maxOvr: 88,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '89-Rated Squad': [
        {
            label: '89 → 88 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 88,
            maxOvr: 89,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '89 → 88 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 88,
            maxOvr: 89,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '90-Rated Squad': [
        {
            label: '91 → 89 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 89,
            maxOvr: 91,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '91 → 89 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 89,
            maxOvr: 91,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],    
    'Mixed Leagues Upgrade': [
        {
            label: 'Mixed Leagues Upgrade (Any)',
            excludeActiveSquad: null,
            ignorePosition: null,
            sortBy: null,
            storage: 'Any',
            quality: null,
            rarity: null,
            minOvr: 45,
            maxOvr: 74,
            league: 'BEL 1',
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'Mixed Leagues Upgrade (Storage)',
            excludeActiveSquad: null,
            ignorePosition: null,
            sortBy: null,
            storage: 'SBC Storage',
            quality: null,
            rarity: null,
            minOvr: 45,
            maxOvr: 74,
            league: 'BEL 1',
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '5 of 10 81+ Player Pick': [
        {
            label: 'L → H Gold Common (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: null,
            rarity: 'Common',
            minOvr: null,
            maxOvr: 80,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Common (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: null,
            rarity: 'Common',
            minOvr: null,
            maxOvr: 80,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '5x 77+ Upgrade': [
        {
            label: 'L → H Gold Common (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Common (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Common',
            minOvr: null,
            maxOvr: null,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '1 of 5 82+ Player Pick': [
        {
            label: 'L → H Gold Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: null,
            maxOvr: 81,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: null,
            maxOvr: 81,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '1 of 3 83+ Player Pick': [
        {
            label: 'L → H Gold Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: null,
            maxOvr: 82,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: null,
            maxOvr: 82,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '3x 87-90 Upgrade': [
        {
            label: '83 → 82 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 82,
            maxOvr: 83,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '83 → 82 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 82,
            maxOvr: 83,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '2x 84+ Upgrade': [
        {
            label: 'L → H Gold Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: null,
            maxOvr: 82,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: null,
            maxOvr: 82,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '10x 84+ Upgrade': [
        {
            label: 'L → H Gold Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 82,
            maxOvr: 83,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: 'L → H Gold Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 82,
            maxOvr: 83,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    '84+ TOTW Upgrade': [
        {
            label: '84 → 83 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 83,
            maxOvr: 84,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '84 → 83 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating High to Low',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 83,
            maxOvr: 84,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
    'Provisions Upgrade': [
        {
            label: '85 Rare (Any)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'Any',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 85,
            maxOvr: 85,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
        {
            label: '85 Rare (Storage)',
            excludeActiveSquad: true,
            ignorePosition: true,
            sortBy: 'Rating Low to High',
            storage: 'SBC Storage',
            quality: 'Gold',
            rarity: 'Rare',
            minOvr: 85,
            maxOvr: 85,
            league: null,
            useConcept: null,
            untradeablesOnly: null,
        },
    ],
};
